export const siteConfig = {
  name: "Empire Spices & Foods Ltd.",
  description: "Empire Spices & Foods Ltd. brings authentic Indian flavours from Nashik to kitchens across the globe with its flagship brand Ram Bandhu.",
  url: "https://esfl.co.in",
  locale: "en_IN",
  language: "en-IN",
  ogImage: "/og.png",
  keywords: [
    "Empire Spices",
    "Ram Bandhu",
    "Indian Spices",
    "Pickles",
    "Papad",
    "Nashik Spices",
    "ESFL",
  ],
  contact: {
    phone: "+91 253 2365288",
    email: "care@esfl.co.in",
  },
  address: {
    street: "Plot No. 18, 19, 20 & 21, Sector - 1, MIDC, Ambad",
    city: "Nashik",
    state: "Maharashtra",
    postalCode: "422010",
    country: "IN",
  },
  socials: {
    facebook: "https://facebook.com",
    instagram: "https://instagram.com",
    twitter: "https://twitter.com",
    linkedin: "https://linkedin.com",
  },
};

export const siteRoutes = [
  {
    path: "/",
    label: "Home",
    title: "Empire Spices & Foods Ltd.",
    description: siteConfig.description,
    priority: 1,
  },
  {
    path: "/about",
    label: "About Us",
    title: "About Us",
    description: "Learn about Empire Spices & Foods Ltd., carrying authentic Indian flavour from Nashik to kitchens worldwide for over three decades.",
    priority: 0.9,
  },
  {
    path: "/our-process",
    label: "Our Process",
    title: "Our Process",
    description: "A look inside our factories' hygiene, precision, and consistency from raw material intake to the sealed pack.",
    priority: 0.8,
  },
  {
    path: "/csr",
    label: "CSR",
    title: "Corporate Social Responsibility",
    description: "Growing with the communities that grow our spices — education, health, environment, and dignified livelihoods.",
    priority: 0.8,
  },
  {
    path: "/media",
    label: "Media",
    title: "Media & Gallery",
    description: "Explore the latest campaigns, news, TV commercials, and photo galleries from Empire Spices & Foods Ltd.",
    priority: 0.7,
  },
  {
    path: "/become-a-partner",
    label: "Become a Partner",
    title: "Become a Channel Partner",
    description: "Join India's leading spice and food network. Partner with ESFL to bring quality, heritage, and taste to millions of kitchens across the globe.",
    priority: 0.8,
  },
  {
    path: "/carrer",
    label: "Careers",
    title: "Careers",
    description: "Grow your career with Empire Spices & Foods Ltd. Join our passionate team dedicated to delivering authentic flavours.",
    priority: 0.7,
  },
  {
    path: "/investor-login",
    label: "Investor Relations",
    title: "Investor Relations",
    description: "Access annual reports, meeting schedules, and live equity tracking for Empire Spices & Foods Ltd. shareholders.",
    priority: 0.7,
  },
  {
    path: "/contact",
    label: "Contact",
    title: "Contact Us",
    description: "Get in touch with Empire Spices & Foods Ltd. Reach our Nashik headquarters for enquiries, partnerships, and support.",
    priority: 0.8,
  },
];
